{{- if and .Values.persistence.sidecar.enabled  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-quorum-sidecar"
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "quorumNode.labels" . | nindent 4 }}
  {{- with .Values.persistence.sidecar.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistence.sidecar.finalizers }}
  finalizers: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.sidecar.storageClassName }}
  storageClassName: {{ .Values.persistence.sidecar.storageClassName | quote }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.sidecar.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sidecar.size | quote }}
  {{- with .Values.persistence.sidecar.selectorLabels }}
  selector:
    matchLabels: {{ toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.persistence.sidecar.dataSource }}
  dataSource: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
