---
# Source: quorum-node/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account
  namespace: quorum
  labels:
    helm.sh/chart: quorum-node-0.6.4
    app.kubernetes.io/name: test-account
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "22.7.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::838158121660:role/eleaflet-poc-secrets
---
# Source: quorum-node/templates/secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-class
  namespace: quorum
spec:
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:us-east-1:838158121660:secret:quorum-node-Jj73xW
        objectType: "secretsmanager"
        jmesPath:
          - path: nodekey
            objectAlias: nodekey
          # Key only required on new network
          - path: key
            objectAlias: key
  provider: aws
